### ISSUE TITLE
A problem for downloading the sequences.

### ISSUE THREAD

**Issue by dingxiao8715** [poeli/EpiCoV_downloader#10] opened 2021-01-04 05:43 UTC
Hello Li,

First of all, I sincerely thank you for writing this script. However, a problem appeared when I ran the command "./gisaid_EpiCoV_downloader.py -u $UNAME -p $PASSWD -hc -le -cg". I'm sure the username and password are correct. The errors are "2021-01-04 13:35 [INFO] GISAID EpiCoV Utility v20.12.14
2021-01-04 13:35 [INFO] Opening browser...
Traceback (most recent call last):
  File "/mnt/g/test/EpiCoV_downloader/gisaid_EpiCoV_downloader.py", line 628, in <module>
    main()
  File "/mnt/g/test/EpiCoV_downloader/gisaid_EpiCoV_downloader.py", line 604, in main
    download_gisaid_EpiCoV(
  File "/mnt/g/test/EpiCoV_downloader/gisaid_EpiCoV_downloader.py", line 171, in download_gisaid_EpiCoV
    driver = webdriver.Firefox(firefox_profile=profile, options=options)
  File "/home/dingxiao/miniconda3/envs/gisaid/lib/python3.9/site-packages/selenium/webdriver/firefox/webdriver.py", line 170, in __init__
    RemoteWebDriver.__init__(
  File "/home/dingxiao/miniconda3/envs/gisaid/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/dingxiao/miniconda3/envs/gisaid/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/dingxiao/miniconda3/envs/gisaid/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/dingxiao/miniconda3/envs/gisaid/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: invalid argument: can't kill an exited process".
I hope you can help me to resolve this problem , thanks!

Best!
Xiao

**Comment by dingxiao8715** [comment] 2021-01-04 05:46
This is my log file.
[geckodriver.log](https://github.com/poeli/EpiCoV_downloader/files/5763219/geckodriver.log)

**Comment by poeli-lanl** [comment] 2021-01-05 00:53
Hi Xiao,

Thanks for your report. I was not able to reproduce your error. The firefox crashed right after being launched by web driver due to `channel error` according to the provided log. There might be something wrong with the compatibility between firefox and the system. I will suggest you to uninstall Firefox from the conda environment. If Firefox is pre-installed on your system, you can try the script again; If not, using your system's package manager (apt-get, yum...etc.) to get Firefox installed and rerun the script.

Also, you might want to check this [post](https://github.com/microsoft/WSL/issues/4964) if you run WSL.

Hope it helps!

Paul

**Comment by dingxiao8715** [comment] 2021-01-06 00:38
Thanks Li~ I'll try again.

**Comment by poeli-lanl** [comment] 2021-02-03 18:14
I'm closing this issue for now. Please reopen if necessary.

**Closed as completed by poeli-lanl** 2021-02-03 18:14 UTC
Labels: bug
